package com.ulyp.core;

public enum TypeTrait {

    CONCRETE_CLASS,
    THROWABLE,
    JAVA_LANG_OBJECT,
    JAVA_LANG_STRING,
    PRIMITIVE,
    NUMBER,
    BOOLEAN,
    INTEGRAL,
    CHAR,
    FRACTIONAL,
    PRIMITIVE_ARRAY,
    NON_PRIMITIVE_ARRAY,
    ENUM,
    COLLECTION,
    MAP,
    INTERFACE,
    TYPE_VAR,
    CLASS_OBJECT,
    UNKNOWN
}
