version: 2.1

jobs:
  jdk-8-build:
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:8.0.442
    steps:
      - checkout
      - run:
          name: "Run gradle build"
          command: "chmod +x gradlew && ./gradlew ulyp-common:check ulyp-storage:check ulyp-agent-core:check ulyp-agent-tests:check -i"
  jdk-17-build:
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:17.0.14
    steps:
      - checkout
      - run:
          name: "Run gradle build"
          command: "chmod +x gradlew && ./gradlew ulyp-common:check ulyp-storage:check ulyp-agent-core:check ulyp-agent-tests:check ulyp-ui:build -i"

workflows:
  build-workflow:
    jobs:
      - jdk-8-build
      - jdk-17-build
